[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
punky_solana_anchor = "H1LbKLGSBTKUrWiPTU6QiPzodkQaAWEqvMXjhiXu3izU"

[programs.devnet]
punky_solana_anchor = "H1LbKLGSBTKUrWiPTU6QiPzodkQaAWEqvMXjhiXu3izU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
